### ISSUE TITLE
cookie只需要RAIL_DEVICEID就可以

### ISSUE THREAD

**Issue by he426100** [v-leonhou/12306#1]

**Comment by v-leonhou** [comment]
可以呢？我回头试试，现在的请求我是完全用的的chrome浏览器的参数请求的

**Comment by he426100** [comment]
借助phantomjs可以自动获取到所需的cookie， 不过我碰到个蛋疼的问题，本地拿得到deviceid，服务器上就不行，window和linux都试了拿不到

[12306.js.txt](https://github.com/v-leonhou/12306/files/1346237/12306.js.txt)
