### ISSUE TITLE
该怎么启动？

### ISSUE THREAD

**Issue by zhenzihui** [v-leonhou/12306#2]
cmd 输入 php start.php
显示：
PHP Fatal error:  Uncaught Error: Call to undefined function pcntl_fork() in C:\Users\zhenz\Documents\php\12306-master\Worker.php:45
Stack trace:
#0 C:\Users\zhenz\Documents\php\12306-master\start.php(31): Worker->run()
#1 {main}
  thrown in C:\Users\zhenz\Documents\php\12306-master\Worker.php on line 45

**Comment by v-leonhou** [comment]
不支持win
